"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
APP_NAME = "辅助记账"
DATA_FILES = ['ui.ui','logo.icns']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'logo.icns',
    'plist':{
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "AuxiliaryBookkeeping",
        'CFBundleIdentifier': "com.metachris.osx.AuxiliaryBookkeeping",
        'CFBundleVersion': "1.0.0",
        'CFBundleShortVersionString': "1.0.0",
        'NSHumanReadableCopyright': u"Copyright © 2021, Power By 崔斐然, All Rights Reserved"
    }
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
